name: Birthday Bot

on:
  schedule:
    - cron: '0 19 * * *'  # Каждый день в 6:00 UTC (9:00 по Москве)
  workflow_dispatch:

jobs:
  check-birthdays:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Check birthdays and send messages
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TZ: Asia/Tashkent
          PROXY_URL: ${{ secrets.PROXY_URL }}
        run: python birthday_bot.py